proxy_hosts:
  - 2ip.ru
  - kaspersky.ru
  - kaspersky.ua
  - drweb.ru
  - mail.ru
  - imgsmail.ru
  - mradx.net
  - 2ch.hk
  - vk.com
  - vkontakte.ru
  - userapi.com
  - kinopoisk.ru
  - ok.ru
  - ok.com
  - mycdn.me
  - ya.ru
  - yandex.ru
  - yandex.ua
  - yandex.net
  - yandex.st
  - cldmail.me
  - yadi.sk
  - yastatic.net
  - webvisor.net
  - auto.ru
  - kinopoisk.ru
